Algoritmo "TABUADA

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor: Antonio Carlos Nicolodi
// Autor(a)    : aluno(a): FELIPE ARGOLO
// Data atual  : 13/09/2023

Var

   // Seção de Declarações das variáveis

   I: INTEIRO
   N: INTEIRO
   SOMA:INTEIRO


Inicio

   PARA I DE 1 ATE 5 PASSO 1 FACA
      ESCREVA (" DIGITE O ", I, "° NÚMERO:" )
      LEIA (N)
      SOMA <- SOMA + N
   FIMPARA

   ESCREVAL ("SOMA:", SOMA)

Fimalgoritmo